
'use server';
/**
 * @fileOverview A flow for sending emails.
 *
 * - sendEmail - A function that sends an email.
 * - SendEmailInput - The input type for the sendEmail function.
 * - SendEmailOutput - The return type for the sendEmail function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const SendEmailInputSchema = z.object({
  to: z.string().describe('The recipient email address.'),
  subject: z.string().describe('The subject of the email.'),
  body: z.string().describe('The body of the email (can be HTML). This will be generated by the flow.'),
});
export type SendEmailInput = z.infer<typeof SendEmailInputSchema>;

const SendEmailOutputSchema = z.object({
  success: z.boolean().describe('Whether the email was sent successfully.'),
  code: z.string().optional().describe('The verification code that was sent.'),
});
export type SendEmailOutput = z.infer<typeof SendEmailOutputSchema>;

export async function sendEmail(input: SendEmailInput): Promise<SendEmailOutput> {
  return sendEmailFlow(input);
}

// This is a placeholder for a real email sending service.
// In a production environment, you would integrate with a service like SendGrid, Mailgun, etc.
const sendEmailFlow = ai.defineFlow(
  {
    name: 'sendEmailFlow',
    inputSchema: SendEmailInputSchema,
    outputSchema: SendEmailOutputSchema,
  },
  async (input) => {
    // Generate a random 6-digit code for 2FA
    const verificationCode = Math.floor(100000 + Math.random() * 900000).toString();
    const emailBody = `
      <h1>Bachat Buddy Two-Factor Authentication</h1>
      <p>Your verification code is: <strong>${verificationCode}</strong></p>
      <p>This code will expire in 10 minutes.</p>
    `;

    console.log(`Simulating email send to: ${input.to}`);
    console.log(`Subject: ${input.subject}`);
    console.log(`Body: ${emailBody}`);
    
    // In a real implementation, you would have your email sending logic here.
    // For now, we'll just return success and the code.
    return { success: true, code: verificationCode };
  }
);

    